AWSTemplateFormatVersion: '2010-09-09'
# Template to setup Glue job using PyRFC to extract SAP Data via Glue VPC Connection. Credential data will be saved in Secret Manager
Parameters:
  GlueJobName:
    Type: String
    Default: GluePyRFCJob_SAP
    Description: Name of the Glue Job to Deploy to extract SAP Data via RFC
  
  S3LinkforPyRFCLib:
    Type: String
    Default: ''
    Description: The S3 URI to the PyRFC Library uploaded to S3 bucket. (e.g. s3://<S3bucket>/<prefix>/<Your whl file name>)

  AvailabilityZoneforGluepyRFC:
    Type: String
    Default: ''
    Description: Availability Zone (e.g. ap-northeast-1a)
  
  SAPVPCSubnetforGluepyRFC:
    Type: String
    Default: ''
    Description: Subnet ID for Glue Network Connection (e.g subnet-xxxxxxx)
   
  SAPVPCSecurityGroupforGluepyRFC:
    Type: String
    Default: ''
    Description: Security group ID for Glue Network Connection (e.g sg-xxxxxxx)

  PyRFCCode:
    Type: String
    Default: ''
    Description: The S3 URI to the PyRFC script uploaded to S3 bucket. (e.g. s3://<your s3 bucket>/<prefix if you has>/pyrfc_read_table.py)
    
  SecretManagerARN:
    Type: String
    Default: ''
    Description: ARN of the Secret Manager created for SAP connection information. (e.g. arn:aws:secretsmanager:<Region>:<AccountID>:secret:<your secret name and specific text>)
    
  DataS3Bucket:
    Type: String
    Default: ''
    Description: The S3 bucket name which will be saved extracted data from SAP.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label: 
          default: AWS Glue Additional Library and Job Script setting information.
        Parameters:
          - S3LinkforPyRFCLib
          - PyRFCCode
      - Label: 
          default: AWS Secret Manager setting information.
        Parameters:
          - SecretManagerARN
      - Label: 
          default: AWS Glue Job and Network connection setting information.
        Parameters:
          - GlueJobName
          - AvailabilityZoneforGluepyRFC
          - SAPVPCSubnetforGluepyRFC
          - SAPVPCSecurityGroupforGluepyRFC
          - DataS3Bucket

Resources:
  GlueJobRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${GlueJobName}-JobRole-${AWS::AccountId}'
      Description: Role for Glue PyRFC Job to Extract data from SAP
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: !Sub '${GlueJobName}-JobRole-${AWS::AccountId}-secret'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref SecretManagerARN
        - PolicyName: !Sub '${GlueJobName}-JobRole-${AWS::AccountId}-logs'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: 'arn:aws:logs:*:*:*:/aws-glue/*'
        - PolicyName: !Sub '${GlueJobName}-JobRole-${AWS::AccountId}-s3'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource: 
                  - !Sub "arn:aws:s3:::${DataS3Bucket}"
                  - !Sub "arn:aws:s3:::${DataS3Bucket}/*"
        - PolicyName: !Sub '${GlueJobName}-JobRole-${AWS::AccountId}-gluejob'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                  - ec2:DescribeVpcEndpoints
                  - ec2:DescribeRouteTables
                  - ec2:CreateNetworkInterface
                  - ec2:DeleteNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeSubnets
                  - ec2:DescribeVpcAttribute
                Resource: '*'
              - Effect: Allow
                Action:
                  - glue:CreateJob
                  - glue:GetConnection
                  - glue:CreateScript
                Resource:
                  - !Sub 'arn:aws:glue:*:${AWS::AccountId}:catalog'
                  - !Sub 'arn:aws:glue:*:${AWS::AccountId}:connection/*'
                  - !Sub 'arn:aws:glue:*:${AWS::AccountId}:job/*'
                  - !Sub 'arn:aws:glue:*:${AWS::AccountId}:script/*'
              - Effect: Allow
                Action:
                  - ec2:CreateTags
                  - ec2:DeleteTags
                Resource:
                  - 'arn:aws:ec2:*:*:network-interface/*'   

  GlueVPCConnection:
    Type: AWS::Glue::Connection
    Properties:
      CatalogId: !Ref AWS::AccountId
      ConnectionInput:
        Description: 'VPC connection to SAP'
        ConnectionType: "NETWORK"
        PhysicalConnectionRequirements:
          SecurityGroupIdList:
            - !Ref SAPVPCSecurityGroupforGluepyRFC
          SubnetId: !Ref SAPVPCSubnetforGluepyRFC
          AvailabilityZone: !Ref AvailabilityZoneforGluepyRFC
        Name:  !Sub '${GlueJobName}-SAPConnection-${AWS::AccountId}'
  
  # Still updating 
  GluePyRFCJob:
    Type: AWS::Glue::Job
    Properties:
      GlueVersion: '3.0'
      Name: !Ref GlueJobName
      Role: !Ref GlueJobRole
      Command:
        Name: glueetl
        PythonVersion: '3'
        ScriptLocation: !Ref PyRFCCode
      DefaultArguments:
        --additional-python-modules: !Ref S3LinkforPyRFCLib
      ExecutionProperty:
        MaxConcurrentRuns: 2
      MaxRetries: 1
      WorkerType: G.1X
      NumberOfWorkers: 2
      Timeout: 2880
      Connections:
        Connections:
          - !Ref GlueVPCConnection
    DependsOn:
      - GlueVPCConnection
      - GlueJobRole